name: Deploy Storybook to Staging

on:
  push:
    branches:
      - develop

env:
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  deploy:
    if: ${{ vars.ENV == 'staging' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install packages
        run: |
          npm ci
      - name: Build
        run: |
          npm run build-storybook
      - name: Define deploy_id
        run: |
          echo "deploy_id=${{ github.job }}-${{ github.run_id }}-${{ github.run_attempt }}" >> $GITHUB_ENV
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.STG_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions-${{ env.deploy_id }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: copy files to s3 bucket
        run: |
          aws s3 sync --delete \
            --exclude "pr-*" \
            storybook-static s3://${{ secrets.STG_BUCKET_NAME }}/dads/html/
      - name: invalidate cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.STG_CF_DIST_ID }} --paths "/dads/html/*"
